name: "tg-domain-relay"

services:
  tg-domain-relay:
    image: .
    container_name: "tg-domain-relay"
    restart: unless-stopped
    networks:
      - tg-domain-relay-proxy
    ports:
      - "8085:8085" # http port
      - "1080:1080" # socks5 port

networks:
  tg-domain-relay-proxy:
    name: tg-domain-relay-proxy
    driver: bridge
    external: false
