DOMAIN_DEPENDENCIES = {
    "github.com": ["githubassets.com", "github.io", "githubusercontent.com", "avatars.githubusercontent.com"],
    "youtube.com": ["googlevideo.com", "ytimg.com", "ggpht.com", "youtube-nocookie.com"],
    "google.com": ["gstatic.com", "googleapis.com", "googleusercontent.com", "googletagmanager.com", "fonts.googleapis.com"],
    "fastly.com": ["fastly.net", "fastly-insights.com"],
    "reddit.com": ["redditstatic.com", "redd.it", "redditmedia.com"],
    "netflix.com": ["nflxvideo.net", "nflximg.net", "nflxext.com"],
    "spotify.com": ["scdn.co", "spotifycdn.com"],
    "twitch.tv": ["ttvnw.net", "jtvnw.net"],
    "instagram.com": ["cdninstagram.com", "fbcdn.net"],
    "facebook.com": ["fbcdn.net", "facebook.net"],
    "twitter.com": ["twimg.com"],
    "x.com": ["twimg.com"],
    "t.co": ["twimg.com"],
    "wikipedia.org": ["wikimedia.org"],
    "microsoft.com": ["msftncsi.com", "office.net", "office.com", "live.com", "azureedge.net"],
    "apple.com": ["mzstatic.com", "apple-dns.net"],
    "amazon.com": ["ssl-images-amazon.com", "media-amazon.com"],
    "cloudflare.com": ["cloudflareinsights.com", "challenges.cloudflare.com"],
    "vercel.com": ["vercel.app", "vercel-dns.com"],
    "netlify.com": ["netlify.app", "netlifyglobalcdn.com"],
    "discord.com": ["discordapp.net", "discord.gg", "discord.media"],
    "slack.com": ["slack-edge.com", "slack-imgs.com"],
    "zoom.us": ["zoomgov.com", "zoom.us"],
    "telegram.org": ["t.me"],
    "whatsapp.com": ["whatsapp.net"],
    "notion.so": ["notion-static.com"],
    "dropbox.com": ["dropboxstatic.com", "dropbox-dns.com"],
    "adobe.com": ["adobestats.net", "adobedtm.com", "typekit.net"],
    "salesforce.com": ["force.com"],
    "oracle.com": ["oraclecloud.com"],
    "akamai.net": ["akamaiedge.net", "akamaihd.net"],
}